info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  serverURL: 'http://localhost:8080'
  controllers:
    defaultScope: singleton
  asset:
    pipeline:
      enabled: true
  reload:
    enabled: true
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
dataSource:
  url: jdbc:mysql://127.0.0.1:3306/crud?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
  dialect: org.hibernate.dialect.MySQLDialect
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: '12345678'
  pooled: true
  jmxExport: true
  dbCreate: update
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
spring:
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
development:
    grails:
      serverURL: 'http://localhost:8080'
      plugin:
        springsecurity:
          secureChannel:
            useHeaderCheckChannelSecurity: false
          portMapper:
            httpPort: 8080
